### ISSUE TITLE
Glad and GLFW file inclusion error in Sandbox

### ISSUE THREAD

**Issue by harshit2608** [Stupefy-Engine/Stupefy#13]
**Describe the bug**

**To Reproduce**
1. Go to ' Stupefy/systems/renderer/renderer.h '
2.  Edit source code ' Remove the comments from glad and glfw header files '
3. Build the solution and See error

**Expected behavior**
When building the Stypefy solution glad/glad.h error will appear.

**Additional context**
Problem might be related to premake not able to correctly link with Sandbox

**Comment by 0xStackRover** [comment]
The issue has been fixed by adding these lines under the sandbox project in premake5.lua file. 
%{Includedir.Glad} and %{Includedir.GLFW}
